channel_targets:
  - flatsurf main
channel_sources:
  - flatsurf,conda-forge,defaults
job:
  - release
  - release
  - release
  - style
  - test36
  - test37
  - coverage
action:
  - release
  - release
  - release
  - style
  - test
  - test
  - coverage
_python:
  - 3.7.* *_cpython
  - 3.6.* *_cpython
  - 3.7.* *_cpython
  - 3.7.* *_cpython
  - 3.6.* *_cpython
  - 3.7.* *_cpython
  - 3.7.* *_cpython
component:
  - libintervalxt
  - pyintervalxt
  - pyintervalxt
  - intervalxt
  - intervalxt
  - intervalxt
  - intervalxt
zip_keys:
  - job
  - action
  - _python
  - component
