# See https://github.com/conda/conda-build/issues/2666 for the missing tag
{% set version = environ.get('GIT_DESCRIBE_TAG', 'untagged')|string|replace('-','_') %}
# conda-smithy assumes that the build number is >= 1000 when building with the new anaconda compilers,
# this probably is not important but make_build_number otherwise complains during the build
{% set build_number = (environ.get('GIT_DESCRIBE_NUMBER')|int + 1000)|string %}
{% set name = name or 'intervalxt' %}
{% set target = target or 'release' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: {{ environ.get('FEEDSTOCK_ROOT', '..') }}

build:
  number: {{ build_number }}
{%- if name == "libintervalxt" %}
  string: {{ target }}_{{ build_number }}
{%- else %}
  string: {{ target }}_py{{ python }}_{{ build_number }}
{%- endif %}
  # e-antic is not available on Windows yet
  skip: True  # [win]
  # e-antic is not available on macOS yet
  skip: True  # [osx]
  # we do not support old versions of Python
  skip: True  # [py < 36]
{%- if name != "pyintervalxt" and target != "test" %}
  # ignore Python version where it does not matter (conda-smithy still renders these but conda-build stops immediately)
  skip: True  # [py != 37]
{%- endif %}
{%- if name == "libintervalxt" %}
  run_exports:
    # We pin the version of libintervalxt exactly since we do not want to
    # bother with incompatibilities in our nightly builds.
    - {{ pin_subpackage(name, exact=True) }}
{%- endif %}

requirements:
  build:
    - libtool
    - automake
    - coreutils
    - {{ compiler('cxx') }}
{%- if target == "style" %}
    - clangdev ==8.0.0
{%- endif %}
  host:
{%- if name != "pyintervalxt" %}
    # compile-time dependencies of libintervalxt
    - boost-cpp
    - e-antic 1.*
    - gmp
    - ppl
{%- endif %}
{%- if name != "libintervalxt" %}
    - python
    - setuptools
{%- endif %}
{%- if name == "pyintervalxt" %}
    - libintervalxt {{ version }} {{ target }}_{{ build_number }}
{%- endif %}
{%- if target in ["test", "coverage"] %}
    # enable test/pyintervalxt tests in ./configure
    - pytest
    - cppyy
    # enable check-valgrind in ./configure
    - valgrind >=3.15.0
{%- endif %}
  run:
{%- if name == "pyintervalxt" %}
    - python
    - cppyy
{%- endif %}

outputs:
  - name: {{ name }}
{%- if target == "release" %}
    script: install-{{ name }}.sh
{%- endif %}
{%- if name == "pyintervalxt" %}
    test:
      imports:
        - {{ name }}
{%- endif %}

about:
  home: https://github.com/flatsurf/intervalxt
  license: GPL3
  license_file: COPYING
  summary: Boshernitzan Algorithm with Interval Exchange Transformations

extra:
  recipe-maintainers:
    - saraedum
