{% set version = '3.1.4' %}
{% set build_number = '2' %}

package:
  name: libintervalxt
  version: {{ version }}

source:
  path: ../../

build:
  number: {{ build_number }}
  # e-antic is not available on Windows yet
  skip: True  # [win]
  # e-antic is not available on macOS yet
  skip: True  # [osx]
  run_exports:
    - {{ pin_subpackage("libintervalxt", max_pin="x") }}

requirements:
  build:
    - libtool
    - automake
    - coreutils
    - {{ compiler('cxx') }}
  host:
    - boost-cpp {{ boost_cpp }}
    - fmt {{ fmt }}
    - gmp {{ gmp }}
    # Require a version without FPU changes https://github.com/conda-forge/ppl-feedstock/issues/8
    - ppl>=1.2=*_1004
  run:
    # Require a version without FPU changes https://github.com/conda-forge/ppl-feedstock/issues/8
    - ppl>=1.2=*_1004

test:
  commands:
    - test -f ${PREFIX}/lib/libintervalxt.so

about:
  home: https://github.com/flatsurf/intervalxt
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: Boshernitzan Algorithm with Interval Exchange Transformations
